In [95]:
import numpy as np
#hw23 Oz

#1
arr1 = np.arange(1,10+1)
arr2 = np.arange(0.5,5+0.25,0.25)
print(arr1, arr2)

[ 1  2  3  4  5  6  7  8  9 10] [0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


In [96]:
#2
arr3 = np.zeros(10)
arr4 = np.zeros((3, 4))
print(arr3, arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [97]:
#3
arr5 = np.linspace(2,12,5)
arr6 = np.linspace(3,9,4)
print(arr5, arr6)

[ 2.   4.5  7.   9.5 12. ] [3. 5. 7. 9.]


In [98]:
#4
arr7 = np.random.rand(2,4)
arr8 = np.random.randint(10,20, (3,3))
arr9 = np.reshape(arr7, (1,8))
print(arr7, arr8, arr9)
#We can only reshape an array if the new shape members count is equal to the old shapes count

[[0.01080092 0.84846201 0.24316678 0.68002726]
 [0.67713974 0.88582741 0.15356567 0.94669413]] [[13 15 12]
 [18 19 17]
 [13 10 14]] [[0.01080092 0.84846201 0.24316678 0.68002726 0.67713974 0.88582741
  0.15356567 0.94669413]]


In [99]:
#5
#When you use a fixed seed, you get fixed random numbers, which is good for keeping the same numbers and still randomized 
#For example, an encryption key like I used in my project was randomaly generated, but now its saved.

In [115]:
#6
lst1 = []
for i in range(5):
    lst1.append(int(input('Enter a number! ')))
arr10 = np.array(lst1)  
print(arr10.max(),arr10.min(),arr10.shape,arr10.argmax(),arr10.argmin())
    


Enter a number!  4
Enter a number!  6
Enter a number!  9
Enter a number!  1
Enter a number!  5


9 1 (5,) 2 3
